# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: my-fastapi-app
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: my-fastapi-app
# #   template:
# #     metadata:
# #       labels:
# #         app: my-fastapi-app
# #     spec:
# #       containers:
# #         - name: my-fastapi-app
# #           image: your-docker-image-name:tag  # Replace with your actual Docker image name and tag
# #           ports:
# #             - containerPort: 8000
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: my-fastapi-service
# # spec:
# #   selector:
# #     app: my-fastapi-app
# #   ports:
# #     - protocol: TCP
# #       port: 8000
# #       targetPort: 8000
# #   type: LoadBalancer  # Adjust based on your Kubernetes environment (LoadBalancer, NodePort, ClusterIP)


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-fastapi-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-fastapi-app
#   template:
#     metadata:
#       labels:
#         app: my-fastapi-app
#     spec:
#       containers:
#         - name: my-fastapi-app
#           image: ritika2310/my-fastapi-app:latest  # Replace with your Docker image name and tag
#           ports:
#             - containerPort: 8000
#           env:
#             - name: SQLALCHEMY_DATABASE_URL
#               value: "postgresql://postgres:root@host.docker.internal:5432/ecommerce1"  # Adjust based on your environment
#           readinessProbe:
#             httpGet:
#               path: /product 
#               port: 8000
#             initialDelaySeconds: 10
#             periodSeconds: 5
#           livenessProbe:
#             httpGet:
#               path: /product 
#               port: 8000
#             initialDelaySeconds: 15
#             periodSeconds: 10
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-fastapi-service
# spec:
#   selector:
#     app: my-fastapi-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8000
#      type: LoadBalancer 


aapiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop-app-deployment 
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: desktop-app   
  template:
    metadata:
      labels:
        app: desktop-app   
    spec:
      containers:
        - name: desktop-app   
          image: desktop-app:latest  
          ports:
            - containerPort: 8000 
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: postgresql://postgres:root@host.docker.internal:5432/ecommerce1 
          readinessProbe:
            httpGet:
              path: /health-check  
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health-check  
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
