# version: '3.8'

# services:

#   app:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - DATABASE_URL=postgresql://postgres:root@localhost:5432/ecommerce1
  

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: ecommerce1
#     ports:
#       - "5432:5432"


  version: '3.8'

  services:
    app:
      build: .
      ports:
        - "8000:8000"
      environment:
        - SQLALCHEMY_DATABASE_URL=postgresql://postgres:root@host.docker.internal:5432/ecommerce1
      
    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: ecommerce1
      ports:
        - "5432:5432"


# version: '3.8'
# services:
#   web:
#     build: .
#     command: uvicorn main:app --host 0.0.0.0 --port 80
#     volumes:
#       - .:/app
#     ports:
#       - 8000:80
#     depends_on:
#       - db
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: ecommerce1
